### ISSUE TITLE
Crashed when viewing (git) difference in vscode.

### ISSUE THREAD

**Issue by uHOOCCOOHu** [rust-lang-nursery/rls-vscode#102]
I'm using vscode 1.14.2 and rls-vscode 0.1.0 .
Reproduce:
1. Use vscode to open any rust repository with git and wait for the rls initialization.
2. Change any `.rs` file.
3. Click `Source control` button on vscode, and you'll see the changed file listed.
4. Click the changed file to compare against previous version, and the rls-vscode will crash immediately.
And you'll see "Extension host terminated unexpectedly. Please reload the window to recover." on the top.

Here's the [crash log](https://gist.github.com/uHOOCCOOHu/1cbc20d0153695e4eef3ab1d6f8fa915).

**Comment by Xanewok** [comment]
This is tracked over at https://github.com/rust-lang-nursery/rls/issues/421.
