### ISSUE TITLE
rustc "mismatched types" error needs more info in tooltip

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rls-vscode#103]
When rustc complains about mismatched types, for example:

```
error[E0308]: mismatched types
  --> src\main.rs:56:57
   |
56 |     let vertices = o.positions.iter().map(|&v| Vector3f(v.0, v.1, v.2)).collect();
   |                                                         ^^^ expected f64, found f32
```

The only information shown for this by rls-vscode in the tooltip is `[rustc] mismatched types`. This could show more information about the actual types expected and found.

**Comment by dnorman** [comment]
I seem to recall that previous versions included this information. Am I imagining things?

**Comment by nrc** [comment]
dup of https://github.com/rust-lang-nursery/rls/issues/17
