### ISSUE TITLE
RLS crash

### ISSUE THREAD

**Issue by pronebird** [rust-lang-nursery/rls-vscode#105]
VScode extension is broken.

```
[Error - 6:13:58 PM] Request textDocument/codeAction failed.
  Message: Invalid request
  Code: -32600 
[Info  - 6:14:07 PM] Connection to server got closed. Server will restart.
[Info  - 6:14:07 PM] Connection to server got closed. Server will restart.
[Info  - 6:14:07 PM] Connection to server got closed. Server will restart.
[Info  - 6:14:07 PM] Connection to server got closed. Server will restart.
[Error - 6:14:08 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by nrc** [comment]
What project were you working on?

**Comment by pronebird** [comment]
We have a private project with workspace setup. It works great with other crate we have. Any way to track down the exact error? It could be nightly bug btw.

**Comment by nrc** [comment]
RLS currently doesn't really support workspace projects. You should be able to open one of the individual workspaces, but probably not the whole project (we're working on this!)

**Comment by nrc** [comment]
This is tracked in a few RLS issues, so closing this one
