### ISSUE TITLE
Create release tags and start versioning

### ISSUE THREAD

**Issue by klausi** [rust-lang-nursery/rls-vscode#109]
The current version of the extension in the marketplace appears to be broken:

```
[Error - 5:46:28 PM] Request textDocument/codeAction failed.
  Message: Invalid request
  Code: -32600 
```

https://github.com/rust-lang-nursery/rls-vscode/releases shows 0 releases, so I'm not sure which code is even uploaded to the VSCode marketplace?

Do you plan start doing regular releases soon? The README says people should use the marketplace version, is this still up to date or do users have the build the extension themselves?

Thanks!

**Comment by nrc** [comment]
> The current version of the extension in the marketplace appears to be broken:

That doesn't indicate it's broken, just that a single message was not handled. The RLS should continue working. (I believe that is fixed on master).

> https://github.com/rust-lang-nursery/rls-vscode/releases shows 0 releases

I've not used tags in the past for this repo. I can start if it is useful.

> Do you plan start doing regular releases soon?

I plan to do another release soon, hopefully this week. And then, hopefully, more regularly. Most changes land in the RLS which is updated separately from the extension, so having an up to date RLS is more important than an up to date extensions. The one in the marketplace is a few weeks old, but not obsolete or anything.

**Comment by klausi** [comment]
Hm ok, I thought "Invalid request" would mean that the extension is sending invalid requests to the RLS and might not be up to date. RLS is 0.1.0-nightly (cb8a590 2017-08-02) on my system, so something else seems to be broken that I need to debug.

I switched back to the other Rust VSCode extension for now at https://marketplace.visualstudio.com/items?itemName=kalitaalexey.vscode-rust , that one works in legacy mode.

And yes, I think Git tags are always useful for tracking changes :-)

**Comment by nrc** [comment]
We now have our first tag for the 0.2.0 release. I'll try to remember to keep making the tags
