### ISSUE TITLE
Cannot goto definition of enum type at enum variant use-site

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rls-vscode#111]
Given the following:

```rust
enum Foo {
    Bar,
    Baz,
}

fn stuff() {
    let x = Foo::Bar;
    let y: Foo = Foo::Baz;
}
```

I can ctrl-click `Foo` in the type declaration of `y`, but I cannot ctrl-click `Foo` in `Foo::Bar` or `Foo::Baz`.

**Comment by nrc** [comment]
This is a known limitation, the RLS only has knowledge about the path as a whole, not its components, so we can only do goto def/type on hover for the last item in the path. Closing since this is tracked elsewhere.
