### ISSUE TITLE
Cannot go to definition of tuple struct at constructor invocation

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rls-vscode#112]
Given the following:

```rust
struct Foo(u32);

struct Baz {}

fn stuff() {
    let x = Foo(1);
    let y = Baz {};
}
```

I  cannot ctrl-click `Foo` in the `stuff` function, but I can ctrl-click `Baz`. The syntax coloring seems to imply that the `Foo` constructor is being recognized as a function invocation.

**Comment by nrc** [comment]
Tracked here: https://github.com/nrc/rls-analysis/issues/77
