### ISSUE TITLE
functions not analyzed if only tests use them

### ISSUE THREAD

**Issue by jackmott** [rust-lang-nursery/rls-vscode#115]
I have a project that includes some modules with functions, and they are called only by tests. Cargo tests builds and runs the tests.  But rls-vscode does not analyze any of the functions at all.

I can create a main.rs that imports the module, and then the file gets analyzed, but unless I use every function in the module, everything gets green squigglys warning that the functions are unused.

Possibly I am arranging something wrong here but it seems like it could be a usability problem when developing libraries.

**Comment by jackmott** [comment]
update:
the following configuration settings seem to resolve the problem:

```
    "rust.cfg_test": true,
    "rust.build_lib": true
```

Perhaps adding a tip about this to the docs?

**Comment by jtremback** [comment]
Dumb question: where do those configs go?

**Comment by Xanewok** [comment]
Hey, glad it's all working now!

@jackmott The documentation for the extension is here https://github.com/rust-lang-nursery/rls-vscode#configuration and should be visible inside VSCode, it also includes the `"rust.cfg_test"` option. What else could we do to help inform the users about possible options?

**Comment by jackmott** [comment]
Looks all good now, I don't think that was in the docs back when I posted this. Or I missed it! I'll close this.

**Comment by Xanewok** [comment]
Great, thanks!
