### ISSUE TITLE
document rls.path

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang-nursery/rls-vscode#119]
I build packages personally, and I don't use rustup. It should search the PATH instead of bailing, and have a config to set the RLS executable path if it makes sense.

**Comment by ishitatsuyuki** [comment]
Seems the config option already exists, but it's completely undocumented.

**Comment by beefsack** [comment]
@ishitatsuyuki which config option did you use to achieve this?

**Comment by ishitatsuyuki** [comment]
"rls.path"

**Comment by beefsack** [comment]
Thanks, worked a treat. Confirmed it worked by setting it to an invalid path and it failed to start.

**Comment by natemara** [comment]
Is there a reason that `rls.path` is not documented?

**Comment by nrc** [comment]
> Is there a reason that rls.path is not documented?

It is only meant for RLS developers to use, and it is documented in the developer docs for the RLS

**Comment by ishitatsuyuki** [comment]
@nrc Can you consider documenting this? I don't use rustup but instead create packages on myself, so the rustup integration isn't an option for me.
