### ISSUE TITLE
RLS 0.2.2 does not start at all

### ISSUE THREAD

**Issue by mcgoo** [rust-lang-nursery/rls-vscode#134]
Thanks for the plugin, I have enjoyed using it for the last several days. Unfortunately it looks like the latest update is broken on my setup.

I'm running the x64 version of VSCode 1.15.1 on Win10 1703. The 0.2.1 plugin was working correctly. Now when I start VSCode I don't get the "RLS: Analysis..." message at all.

I get no indication that VSCode is trying to start the extension at all - I have tried various combinations of `"rust-client.showStdErr": true` `"rust-client.logToFile": true` and in the environment `RUST_LOG=rls=debug` and I get no logfile, no output in the output tab, and as far as I can see, no rls.exe process running. I tried opening a rust file and editing it on each run to see if that was required to kick it off.

I ran `rustup update` and `cargo install rustfmt-nightly`. The `rls` binary starts correctly when run from the command line, as does `rustfmt`.

VSCode does know about the configuration settings for the extension. 

I tried a project newly created with `cargo new --bin` and that does not work.

**Comment by nrc** [comment]
Can you run the RLS from the command line? `rls --version` should give you the version and quit. Could you also try running vscode with `--verbose` to see if it tells you anything more?

**Comment by mcgoo** [comment]
Ok, the extension is working again for me thanks! The `--verbose` put me on the right track - I removed and reinstalled the extension and it worked. (I had previously disabled it and re-enabled it but not removed it completely.) I did not think to examine the plugin directory before I reinstalled.

`rls 0.1.0-nightly (5d4bbd9 2017-08-07)`

`[14004:0824/224110.125:INFO:CONSOLE(28)] "Error: ENOENT: no such file or directory, open 'C:\Users\jim\.vscode\extensions\rust-lang.rust-0.2.2\language-configuration.json'", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (28)`

**Comment by pravic** [comment]
I've had the similar problem: RLS just was showing a `RLS analysis: starting up` message and that's all. However, updating to the latest nightly solved it.

**Comment by pravic** [comment]
P.S. `0.2.2 - 2017-09-21` - a release from the future?

**Comment by mcgoo** [comment]
I'm going to close this since is works for me after a reinstall of the plugin and I can't repro. It seems more likely to be a vscode bug than anything.
