### ISSUE TITLE
Show definition of function?

### ISSUE THREAD

**Issue by shinchiro** [rust-lang-nursery/rls-vscode#139]
Is it possible to find definition of  functions like IntelliJ Rust did?

Example:
![image](https://user-images.githubusercontent.com/9623615/29765101-64194dae-8c0c-11e7-80ed-c9ce06af2a88.png)

**Comment by nrc** [comment]
Yes, peek definition, does this - Ctrl+Shift+F10

**Comment by shinchiro** [comment]
Tried before but nothing appear. When looked at rls's output, it showed ``[Info  - 6:54:11 PM] Connection to server got closed. Server will restart.``

**Comment by jonasbb** [comment]
You are trying to go to a definition in the standard library, which is not supported. Try it with a function in your current crate.

**Comment by shinchiro** [comment]
Yes. Is it planned to support std lib in future?

**Comment by nrc** [comment]
Yes, I plan to support it, but it is a little complex. Hopefully in the next few months
