### ISSUE TITLE
rust-client.showStdErr is not respected

### ISSUE THREAD

**Issue by Xanewok** [rust-lang-nursery/rls-vscode#149]
Updating deps in https://github.com/rust-lang-nursery/rls-vscode/pull/148 pulled a fix https://github.com/Microsoft/vscode-languageserver-node/commit/8ed63637d95e1dbd7ad0b6e5d71195a7a88943b2, which now always logs the stderr of the language server to the related output window in the VSCode.

@nrc do you think we could remove the `rust-client.showStdErr` option and the related [hack](https://github.com/rust-lang-nursery/rls-vscode/blob/master/src/extension.ts#L144) now?

**Comment by nrc** [comment]
Yeah, assuming we test and this works, lets get rid of the old stuff
