### ISSUE TITLE
Problems and hints broken if the path of the file contains a Unicode combining diacritic.

### ISSUE THREAD

**Issue by hannni** [rust-lang-nursery/rls-vscode#151]
The code I write is in a directory called `Wörk`. The `ö` here is o plus the combining diaresis (`Wo\xCC\x88rk`), as I am using macOS which normalizes file names as decomposed.

Now if I have some errors in my code, they show up in the problems pane. However if I click them Visual Studio Code does not jump to the errors but gives me the following error instead:

> Unable to open 'fmt.rs': File not found (/Users/hanni/WoÌrk/svg_util/src/fmt.rs).

Note that `\xCC` is `Ì` in ISO-8859-1, and there's an invisible `HTS` control character after that, which is `\x88` in ISO-8859-1.

The error did not occur when using alexey's Rust extension with RLS. So I guess this extension somewhere must have a conversion from ISO-8859-1 to unicode.

The go to definition feature is not broken.

**Comment by nrc** [comment]
Hmm, it is very strange that the two extensions behave differently since the problem panel is handled entirely by VSCode. I could imagine we had a bug on the RLS side, but that should affect other extensions too. Perhaps there is some way to configure the problem panel or string handling or something in VSCode?

**Comment by nrc** [comment]
This issue has some discussion of setting languauge-specific text encodings: https://github.com/Microsoft/vscode/issues/19890. I wonder if we should explicitly set utf8 for Rust?

**Comment by nrc** [comment]
@hannni do you have any settings configuring the text encoding? What does VSCode say the encoding for the file is? (Appears in the bottom-right status bar).

**Comment by hannni** [comment]
My text encoding is UTF8 and I don't have any settings regarding file encodings.
This issue should also be orthogonal to the file encoding, because it is about file name encoding (which should always be UTF8 on macOS). What makes me wonder a bit is that the Go to definition, Peek definition and Find all references features works perfectly, even though it should pass the same file names.

I played a bit around to see if also the error message shows the corruption, so I added a "ö" (`"\xC3\xB6"`, `"Ã¶"` when reinterpreted as ISO-8859-1) as an unexpected token, and indeed it is also corrupted. However it is corrupted in both alexey's extension and this one. So this seems to be another additional bug.

The problem in Alexey's extension:

> file: 'file:///Users/hanni/Wo%CC%88rk/svg_util/src/fmt.rs'
> severity: 'Error'
> message: 'expected one of `.`, `;`, `?`, `}`, or an operator, found `"Ã¶"`
> unexpected token'
> at: '138,9'
> source: 'rustc'

The problem in this extension:

> file: 'file:///Users/hanni/Wo%C3%8C%C2%88rk/svg_util/src/fmt.rs'
> severity: 'Error'
> message: 'expected one of `.`, `;`, `?`, `}`, or an operator, found `"Ã¶"`
> unexpected token'
> at: '138,9'
> source: 'rustc'

**Comment by Xanewok** [comment]
Investigation report:

url_serde decodes these urls (properly) into:
`file:///home/xanewok/W%C3%B6rk/example/src/my_module.rs`
however, these are somehow reserialized/sanitized again and in `publishDiagnostics` we return:
`file:///home/xanewok/W%C3%83%C2%B6rk/example/src/my_module.rs`
which vscode can't handle anymore.

I'll look more into it.
