### ISSUE TITLE
Continue Comment on New Line

### ISSUE THREAD

**Issue by DSpeckhals** [rust-lang-nursery/rls-vscode#153]
Other language extensions in VS Code (such as Python) continue comments on a new line when pressing `enter`. This makes typing a little more fluid, especially when writing long doc comments. I would be happy to work on this; I will work on the PR if there is consensus that this is a good idea.

Current functionality:

```rust
/// Tests a scenario<newline>
<-- Cursor here
fn test() {
}
```

Proposed functionality:

```rust
/// Tests a scenario<newline>
/// <-- Cursor here
fn test() {
}
```

**Comment by nrc** [comment]
Yep, this sounds like a great feature. It would be great if you could work on a PR!
