### ISSUE TITLE
Are we starting the RLS twice?!

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#159]
No idea how this is happening, but from my console logging, it looks like we're launching the RLS twice. I'm using `rls.path`, I'm not sure if this is happening with rustup. And I have no idea why it is happening. But if we're doing twice as much work using twice the resources we need to, that seems bad.

**Comment by smt923** [comment]
On windows, using rustup, rls appears to start a second process of rls that lasts under a second, I'm not sure if this is related or not (could be possible this is totally expected, I don't know much about RLS), I'm not entirely sure how to best investigate this but did get a gif of all processes that have 'rls' or 'rustup' in their name/path/etc that launch when starting vscode in a rust project: 

![gif](https://i.imgur.com/BtFNQy5.gif)

**Comment by Xanewok** [comment]
@nrc isn't that running the compiler shim via the _rls_ process?

**Comment by nrc** [comment]
Yeah, the RLS starting the RLS is the shim, but I had some logging in `run_server` that was being hit twice and I'd only expect that to happen in the non-shim case.

Oh, I see what we're doing - d'oh! We're not exiting after running the shim, then go on to start the server.

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang-nursery/rls/commit/4a684eb9620a056fdabc98a5fb3c30510ca31a8d
