### ISSUE TITLE
rls-vscode doesn't hierarchically organize symbols

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang-nursery/rls-vscode#164]
I'm using the [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) extension. With files for other languages, this displays a hierarchical tree of symbols, so that for instance local variables are children of the function they're contained in. But with Rust files, it's just a flat list, so that the global list of symbols is cluttered up with lots of local variables.

I don't know anything about the structure of VS Code extensions, but I'm assuming this is caused by how rls-vscode reports symbols to VS Code.

**Comment by ExpHP** [comment]
duplicate of #124?

**Comment by mikebenfield** [comment]
Ah, right, sorry.
