### ISSUE TITLE
I can't edit single .rs files

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang-nursery/rls-vscode#165]
I am using the vscodevim extension in addition to rls-vscode.

If I 

* edit a Rust project, or
* edit a file for another language, or
* edit a single Rust file with either rls-vscode or vscodevim disabled,

then everything works fine.

But if I try to edit a single standalone .rs file with rls-vscode and vscodevim enabled, key presses have no effect in VS Code. Although I don't know for certain whether to blame rls-vscode or vscodevim, since it works fine with extensions for other languages, I'm guessing the problem is rls-vscode doing something odd.

**Comment by Xanewok** [comment]
That's weird, I have rls-vscode (0.3) and vscodevim (0.10.1) enabled in VSCode 1.16.1, just opened a new .rs file and started editing in Vim-like mode. Insert/Normal mode and simple stuff like `$`, `0` or `dd` worked.
Would you please find a minified repro case, if that still happens for you?

**Comment by mikebenfield** [comment]
Well, I do `code newfile.rs`, repeatedly press `o`, and nothing happens. And I actually now see that in the bar at the bottom I get the message "RLS: starting up" that just stays forever.

**Comment by nrc** [comment]
dup of #108
