### ISSUE TITLE
Allow to use system-instelled rust

### ISSUE THREAD

**Issue by suhr** [rust-lang-nursery/rls-vscode#166]
In vscode-rust I can use system-installed rust and rls by setting a few options in the config:

```
    "rust.rustup": {
        "toolchain": "system (default)",
        "nightlyToolchain": "system (default)"
    },
    "rust.rls": {
        "useRustfmt": false,
        "executable": "rls-bin-999"
    }
```

It would be nice to be able to do the same in rls-vscode.

**Comment by nrc** [comment]
You can set the path to the rls using `rls.path`. There is a PR in the queue for setting the rustup path.

**Comment by suhr** [comment]
> You can set the path to the rls using `rls.path`.

I see. There's no such option in `package.json` though.

**Comment by nrc** [comment]
> There's no such option in package.json though.

Yeah, it is deliberately somewhat hidden since it has caused issues for users who have set it then forgotten. It is documented in debugging.md, iirc
