### ISSUE TITLE
Open a parent directory that doesn't contain Cargo.toml fails

### ISSUE THREAD

**Issue by drager** [rust-lang-nursery/rls-vscode#170]
Hey,

I'm having a folder that doesn't only contain my Rust code but also contains other code, that aren't written in Rust. My folder structure looks like this: 
```
myfolder
├── server
│   ├── Cargo.lock
│   ├── Cargo.toml
│   ├── src
│   │   ├── lib.rs
│   │   └── main.rs
└── ui
    ├── src
    │   ├── Not Rust code
```

So I want to open this folder once in `vscode`in order to smoothly develop the server code and the ui code. I could open the `server` and the `ui` folders separately but that's not ideal for me.

So when I have build on save on I get this error:
```
error: could not find `Cargo.toml` in `myfolder` or any parent directory 
```

which is the result of this folder structure.

**Comment by nrc** [comment]
cc #108 

This is mostly an RLS issue, there are a few issues over there tracking this sort of thing. I don't think it will be too hard to address, but it won't be in the near future, sorry.

**Comment by jwatt** [comment]
FWIW https://github.com/pcwalton/pathfinder/ is one such repo that is hurt by this.
