### ISSUE TITLE
“Go to Definition “  ERROR

### ISSUE THREAD

**Issue by hustlibraco** [rust-lang-nursery/rls-vscode#171]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:45:46.804Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-markdownlint|Dav|0.10.1
python|don|0.7.0
vscode-great-icons|emm|2.1.16
sublime-keybindings|ms-|2.9.1
vscode-icons|rob|7.14.0
rust|rus|0.3.1

(2 theme extensions excluded)

---

Steps to Reproduce:

First I was writing rust in vscode, it recommended me install Rust(rls)，and i execute:
`rustup component add rust-src`
then my code can  auto-complement, but can't go to definition, it points a file that doesn't exist.
`无法打开“cmp.rs”: 找不到文件(file:///d:/Program Files/Microsoft VS Code/src/libcore/cmp.rs)。`
and the real Rust std in 
`D:\Rust\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src`.

I don't know this is a bug or is a mistake for some setting.

Reproduces without extensions: Yes/No

**Comment by hustlibraco** [comment]
useless when setting `RUST_SRC_PATH` envir

**Comment by nrc** [comment]
This is tracked at https://github.com/rust-lang-nursery/rls/issues/454

**Comment by umitdemirci** [comment]
```bash
  $ rustup install nightly
  $ rustup default nightly
  $ rustup component add rls-preview rust-analysis rust-src
  $ rustup update
```
Apply the commands, they will fix it.
