### ISSUE TITLE
rustup should be an optional dependency

### ISSUE THREAD

**Issue by steveeJ** [rust-lang-nursery/rls-vscode#174]
I understand that `rustup` simplifies things for most people and is highly valuable to install tools on most systems.
However, I prefer to install these tools via `nix` with the rust-overlay available at [mozilla/nixpkgs-mozilla](https://github.com/mozilla/nixpkgs-mozilla)

I suggest to introduce a mode of operation where all tools are simply attempted to be taken from $PATH and make the user responsible for having them there. 
`rustc --print sysroot` and friends should still allow auto-detection of the environment.

**Comment by nrc** [comment]
This is possible today using a setting in VSCode (rather than $PATH) (though deliberately not well-documented since it can be an unstable way to run). See https://github.com/rust-lang-nursery/rls-vscode/blob/master/contributing.md#via-an-executable
