### ISSUE TITLE
Workspace mode not working with "plietar/librespot"

### ISSUE THREAD

**Issue by Hoeze** [rust-lang-nursery/rls-vscode#176]
Hi,
I tried using the workspace mode of _vscode Insider_ with following project:
https://github.com/plietar/librespot/

However, it does not seem like vscode watches the sub-projects in this folder.
There are no recommendations when typing `"librespot::audio::" + <ctrl> + <space>`.

My settings:
```
{
    "rust.workspace_mode": true,
    "rust.unstable_features": true
}
```
I am using an up-to-date rust nightly tool chain.

**Comment by nrc** [comment]
We've not tried to integrate with VSCode's workspace more, so I wouldn't expect this to work. However, it is something I would like to get working in the future.

**Comment by nrc** [comment]
https://github.com/rust-lang-nursery/rls/issues/469
