### ISSUE TITLE
Can't open std lib source files

### ISSUE THREAD

**Issue by cetra3** [rust-lang-nursery/rls-vscode#177]
Not sure where this bug lies, but it appears as though some of the std lib files are not loaded correctly?

Using rustup nightly on mac OS X

I also need to set `rust.goto_def_racer_fallback` to `true` to have some of the files loaded.   By default it doesn't work.

With this file (from a `cargo new --bin`):

```
use std::collections::BTreeMap;
use std::fs::File;

fn main() {
    println!("Hello, world!");
}
```

I can load the`BTreeMap` definition just fine by `cmd + click` and it works with racer:

```
$ racer find-definition 1 27 src/main.rs
MATCH BTreeMap,135,11,/Users/cetra/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/../liballoc/btree/map.rs,Struct,pub struct BTreeMap<K, V>
END
```

I **can't** load the `File` definition, as it looks for it in the current working directory.  It gives the generic `Unable to open ... File not found`:

![screen shot 2017-10-25 at 1 58 40 pm](https://user-images.githubusercontent.com/6415435/31979158-afd2751a-b98c-11e7-912c-b47b4f17a9fe.png)

But this works OK with racer:

```
$ racer find-definition 2 17 src/main.rs
MATCH File,89,11,/Users/cetra/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/fs.rs,Struct,pub struct File
END
```

**Comment by 0qdk4o** [comment]
same problem. `racer find-definition ...` works fine.

OS: Win8.1

**Comment by nrc** [comment]
https://github.com/rust-lang-nursery/rls/issues/227

**Comment by cetra3** [comment]
@nrc, does that Issue cover the scenario when you have installed everything via rustup and it's still not working

**Comment by nrc** [comment]
> does that Issue cover the scenario when you have installed everything via rustup and it's still not working

yes
