### ISSUE TITLE
Choose a channel for the RLS based on the current Rustup default.

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#179]
E.g., if the user is using the stable channel by default, then we should use the stable channel for launching the RLS with Rustup.

This should not be used, if the user has set `rust-client.channel`, which means we will need to change the default for that setting to `null` rather than `"nightly"`.

To get started, look at rustup.ts. I think you'll need to parse the result of `rustup show`.

**Comment by lnicola** [comment]
I wonder if there shouldn't be a `rustup run default foo` that uses the default channel instead.

**Comment by lnicola** [comment]
@nrc is there any reason to invoke `rls` through `rustup` when the channel hasn't been customized?

**Comment by nrc** [comment]
Yeah, that might work. I can't think of a reason why it would not. We'd need to experiment to make sure.

We'd need to use rustup if just calling `rls` didn't work (to install RLS or whatever), but then I think we could just use rustup without specifying a channel to get the default.

**Comment by lnicola** [comment]
> I can't think of a reason why it would not.

Maybe `rustup` is in `PATH`, but `~/.cargo/bin` isn't.

> I think we could just use rustup without specifying a channel to get the default.

The thing is that `rustup run` seems to require a channel name.

**Comment by lnicola** [comment]
I opened https://github.com/rust-lang-nursery/rustup.rs/pull/1279, maybe we'll get this.

**Comment by ctaggart** [comment]
Looks like the latest nightly for Mac is missing `rls-preview`, so I just had to install the one from yesterday:
```
rustup install nightly-2018-09-22
rustup default nightly-2018-09-22
rustup component add rls-preview rust-analysis rust-src
```
