### ISSUE TITLE
Wrong search paths for the standard lib

### ISSUE THREAD

**Issue by AnyCPU** [rust-lang-nursery/rls-vscode#189]
Windows 10 Pro 64 bit, Rust rls 0.3.2, rustc 1.23.0-nightly (e21df8020 2017-11-13)

I get a lot of errors like that

> Unable to open 'cmp.rs': File not found (file:///c:/Program Files/Microsoft VS Code/src/libcore/cmp.rs

when I press the F12.

I think something is wrong and either stable or nightly installation paths should be used.

Example code:
```rust
extern crate rand;

use std::io;
use std::cmp::Ordering;
use rand::Rng;

fn hello(){ println!("{}", "Hello!")}

fn main () {
    println!("Guess the number!");
    let secret_number = rand::thread_rng().gen_range(1, 100);
    println!("Please input your guess.");
    let mut guess = String::new();
    io::stdin().read_line(&mut guess).expect("Failed to read line");
    println!("You guessed: {}", guess);
    let num : u32 = guess.trim().parse().expect("Please type a number!");
    match num.cmp(&secret_number) {
        Ordering::Less => println!{"Too small!"},
        Ordering::Greater => println!("Too big!"),
        Ordering::Equal => println!("You win!")
    }
    hello();
}
```

**Comment by nrc** [comment]
This is a known issue and is tracked on the RLS issue, there is even a PR under review to fix it, so hopefully it will be addressed soon.
