### ISSUE TITLE
RLS cannot find rustc

### ISSUE THREAD

**Issue by vasily-kirichenko** [rust-lang-nursery/rls-vscode#190]
![1](https://user-images.githubusercontent.com/873919/32978204-63ff4bca-cc4e-11e7-945f-d74503ea169a.gif)

Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T21:22:49.932Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by vasily-kirichenko** [comment]
Adding `RUSTC` env var = `c:\Users\<me>\.cargo\bin\rustc.exe` has not helped.

**Comment by Yanpas** [comment]
Same on Windows 10:
`thread '<unnamed>' panicked at 'need to specify SYSROOT or RUSTC env vars, or rustc must be in PATH', src\libcore\option.rs:878:4`

**Comment by jonasbb** [comment]
This bug is already reported and fixed: https://github.com/rust-lang-nursery/rls/issues/544
Simply run `rustup update` to fix the problem. Any nightly version after 2017-11-12 should work.

**Comment by vasily-kirichenko** [comment]
I confirm the bug is fixed.
