### ISSUE TITLE
cargo fmt and vs code autosave formatting result in different outputs

### ISSUE THREAD

**Issue by dreuter** [rust-lang-nursery/rls-vscode#192]
Hi :)

Thanks for this great vs code extension :)

I am using vs code with this version:
```
Version 1.18.1
Commit 929bacba01ef658b873545e26034d1a8067445e9
Date 2017-11-16T18:34:22.110Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
and Rust (rls) version 0.3.2

When I write a simple program like this (`cargo new test-rustfmt-vscode` and replace lib.rs with these contents):
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        test();
        assert_eq!(2 + 2, 4);
    }
    type VeryLongName = i32;

    fn test(_a: VeryLongName,
            _b: VeryLongName,
            _c: VeryLongName,
            _d: VeryLongName,
            _e: VeryLongName) {
        ()
    }
}
```
and autoformat with `cargo fmt` nothing changes.

If I run `Format Document` in vscode it results in this:
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        test();
        assert_eq!(2 + 2, 4);
    }
    type VeryLongName = i32;

    fn test(
        _a: VeryLongName,
        _b: VeryLongName,
        _c: VeryLongName,
        _d: VeryLongName,
        _e: VeryLongName,
    ) {
        ()
    }
}
```

Did I miss some obvious setting or is this a reproducible bug?

Also probably related: #122 #132

**Comment by nrc** [comment]
It looks like you are using an old version of rustfmt locally. Perhaps you are using the `rustfmt` crate instead of `rustfmt-nightly`?

**Comment by dreuter** [comment]
Yes, that was the problem :+1: 

Sorry to bother you with this. I did not know about these changes in the rust autoformatter.
