### ISSUE TITLE
rls-preview component is missing - too-new a nightly?

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang-nursery/rls-vscode#216]
I updated my nightly toolchain to the very latest (`rustup update nightly`) for Rustfmt (rust-lang-nursery/rustfmt#2304) and now the extension says it cannot install new `rls-preview` component. I did this manually by doing `rustup component add rls-preview` and it says *toolchain 'nightly-x86_64-apple-darwin' does not contain component 'rls-preview' for target 'x86_64-apple-darwin'*. Does this just mean my nightly is too new and the extension doesn't work with it yet?

**Comment by kjeremy** [comment]
It looks like it disappeared in the latest nightly again.

**Comment by RReverser** [comment]
This is repo about VSCode extension, not RLS in general. The existing issue for this is https://github.com/rust-lang-nursery/rls/issues/611.
