### ISSUE TITLE
Warn nightly users if rls is missing in the active toolchain

### ISSUE THREAD

**Issue by humean** [rust-lang-nursery/rls-vscode#217]
So I've been fighting for the past couple hours with `rls-preview` on the latest nightly build after doing an unwise `rustup update`. Turns out rls is missing in the latest nightly and has been missing on and off for the past few weeks due to breaking changes in nightly (as is to be expected). 

https://github.com/rust-lang-nursery/rls/issues/611

While trying to work out what was the last working nightly/rls release I saw it mentioned in the issue linked above that rls has a release on stable now (yay!), and sure enough setting  `rust-client.channel` to `stable` got rls working again with this extension. Might it make sense to default to stable rather than asking the user if they want to install the latest nightly, which has a small chance of missing `rls-preview`?

**Comment by Xanewok** [comment]
Current design, as in https://github.com/rust-lang-nursery/rls-vscode/issues/179, is to default to user's current default toolchain.

I do recognize that ergonomics regarding rustup update with possibly missing rls component on nightly (hopefully fixed later by https://github.com/rust-lang-nursery/rustup.rs/issues/1277) are far from perfect and need a lot of work. Also thanks to https://github.com/rust-lang/rust/pull/46554 tool management will be easier and so hopefully rls breakage should occur a lot less frequently from now on.

One idea how to improve the ergonomics is to warn nightly users if active toolchain has no rls component and to detect and suggest newest nightly that has the component available. I'll change the title to better reflect work left to do.

**Comment by humean** [comment]
Yes, it makes much better sense to have it default to the active toolchain over stable.

**Comment by humean** [comment]
I think this has now been address. vscode-rls defaults to the default toolchain set my rustup, and rustup no longer updates nightly if there is no upgrade path for a something like RLS.
