### ISSUE TITLE
Activation event when opening a Rust project

### ISSUE THREAD

**Issue by Aidiakapi** [rust-lang-nursery/rls-vscode#219]
Currently the extension activates when opening a Rust file, which is fine, but I think it makes sense for the extension to also activate when there is a `Cargo.toml` at the *root* of the workspace that's opened. It could make activation a bit quicker, and prevent a bit of waiting on RLS to start up.

A matter of adding: `"workspaceContains:Cargo.toml"` to the [`package.json`](https://github.com/rust-lang-nursery/rls-vscode/blob/master/package.json#L36).

Just a tiny suggestion.

**Comment by nrc** [comment]
This seems like a great idea!

**Comment by Aidiakapi** [comment]
Alright, I'll try to pull the source tomorrow, add the modification, test it, and submit a PR.

**Comment by Aidiakapi** [comment]
Merged, so closing :).
