### ISSUE TITLE
Feature request: auto import

### ISSUE THREAD

**Issue by Geobert** [rust-lang-nursery/rls-vscode#221]
It would be very useful to have a way to automatically add missing `use` (like intelliJ-rust is doing since version 63)

**Comment by nrc** [comment]
This pretty much works - if you just use a type, then you get a lightbulb next to the error, which should be able to insert the required import. The UI here is not great, it would be nice to do it silently, but that is a lot more work. It is tracked in the RLS wishlist issue.
