### ISSUE TITLE
[request] Implement line-range formatter

### ISSUE THREAD

**Issue by fzzr-** [rust-lang-nursery/rls-vscode#228]
**Please** implement line-range formatter. Currently it's not.

How it (should) works:

In the next file `demo.rs` with content:
```rust



struct Foo {x:i8 ,y  :  i8
       }
struct Bar {x:i8 ,y  :  i8}
    
```
- select line 6 (with `struct Bar {x:i8 ,y  :  i8}`)
- `⌘+P`, type `Format Selection`.

**Comment by nrc** [comment]
This is done on the vscode/rls side, but needs some work in rustfmt - see https://github.com/rust-lang-nursery/rls/issues/333 for some discussion.
