### ISSUE TITLE
Non-working state for integration tests

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang-nursery/rls-vscode#232]
Even after setting `rust.cfg_test=true`, `rls-vscode` doesn't verify the `tests` directory.

**Comment by kanerogers** [comment]
I'm also having this same issue. Any ideas? 😢

**Comment by rocallahan** [comment]
Recent RLS build support a `rust.all_targets` option. If you're using such a build you can set `"rust.all_targets": true` in the settings.
