### ISSUE TITLE
Handle rust-client.* configuration value changes

### ISSUE THREAD

**Issue by Xanewok** [rust-lang-nursery/rls-vscode#233]
Currently we lazily initialize the configuration once, at extension startup and later we don't update it, even on related `rust-client.*` configuration value updates.
Probably lazily initializing it from initial user settings is good, but we need to also update changing the values on the go (e.g. changing toolchain used), see https://github.com/rust-lang-nursery/rls-vscode/pull/220#discussion_r159567580.

**Comment by chuck-flowers** [comment]
I think I have a solution written up now that calculates each of the properties lazily each time the value is read. 

This is my first OSS contribution so I was wanting a little guidance with how to submit the pull request. The work is currently in a local branch on my computer that points to a forked version of this repo. I'm assuming I should do the following steps.

1. Make sure my changes are committed to my local branch
2. Push the local branch to my fork
3. Make a pull request for the branch in my fork to a branch in this repo

My question, is which branch should I make the pull request for? Sorry to have to this basic procedural question.

**Comment by Xanewok** [comment]
You’re right, that’s how the process looks like. The PRs should be done against the master branch here.

GitHub also makes it easier to contribute in general - once you push your branch to your fork, you’ll see a yellow message, on either your fork’s or this repo’s main github site, along the lines of: „You recently pushed chuck-flowers/branch_name” - it also exposes a handy button that can create the initial PR against the upstream repo. The only thing you’ll have to do is fill the PR message.

**Comment by chuck-flowers** [comment]
Ok thanks. I'll finish testing and make the PR shortly.
