### ISSUE TITLE
Doesn't work with stable toolchain out of the box

### ISSUE THREAD

**Issue by tomkv** [rust-lang-nursery/rls-vscode#243]
### Steps to reproduce:

1. Install current stable rustc, rust-std, rust-src, rust-docs, rust-analysis, rls-preview, cargo (currently 1.23.0), using `rustup component add rls-preview rust-analysis rust-src`. Put `.cargo/bin` into the `$PATH`, make sure the changed path is applied to the current session.
2. Install vscode and rls-vscode from the marketplace (currently 0.3.2). No user preferences are set.
3. Create a new, empty project with `cargo init --bin`
4. Open the project folder in vscode and open the generated `src/main.rs` in vscode.

These steps reproduce what a new user would do.

### Result:
The user will get the following messages:
- Warn: _RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot._ [Close]
- Info: _nightly toolchain not installed. Install?_ [Yes][Close] ([Close], we want to avoid breakage when the nightly is missing rls)
- Error: _Couldn't start client Rust Language Server._ [Close]

### Expected result:
When the stable release with all required components is available, the addon should a) not to offer to install nightly toolchain b) use the toolchain available.

### Possible workaround:
The user can set the preference `rust-client.channel` to `stable`. However, the initial value is not autodetected, and the default is `nightly`, leading to the confusion.

**Comment by Xanewok** [comment]
Autodetection was implemented in #220, so this should be more or less fixed when the code including the change is published.

**Comment by tomkv** [comment]
Great, thanks!
