### ISSUE TITLE
Option to only re-analyze on save

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rls-vscode#252]
I have an old dual-core machine, and every time I type a character, RLS fires up and basically does a rustc incremental recompilation, using close to 100% cpu. It makes the editor sluggish when I'm typing, and wastes power.

It would be nice if there was an option to only incrementally recompile (and show errors, etc.) when the document is saved, instead of whenever any single change is made to the editor buffer. Or at least have a timeout or something, so it doesn't burn CPU every time a character is typed.

**Comment by nrc** [comment]
It exists! Set `rust.build_on_save` to true.
