### ISSUE TITLE
Help text missing when type is not in scope

### ISSUE THREAD

**Issue by henriiik** [rust-lang-nursery/rls-vscode#255]
Hello!

I ran into an issue that you might not be aware of, I searched but I did not find anything about it.

When a type is not in the scope, rustc gives a nice error message suggesting from where it can be imported. 

```sh
error[E0412]: cannot find type `PathBuf` in this scope
  --> src/main.rs:15:16
   |
15 | fn index(file: PathBuf) -> Result<Html<String>, NotFound<String>> {
   |                ^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
   |
7  | use std::path::PathBuf;
   |
```

When this error is displayed inline in VSCode, everything after `help:` is cut off. I have attached a screenshot showing it "in action".

<img width="952" alt="screen shot 2018-02-11 at 12 57 41" src="https://user-images.githubusercontent.com/392416/36073173-578cefde-0f2c-11e8-8dc1-ff8cc5124fd1.png">

Thanks for all your hard work, the extension is awesome!

**Comment by henriiik** [comment]
I just realised that there is a quick fix item, that will import it. Feel free to close this if you think it's not worth doing anything about :)

**Comment by nrc** [comment]
This should be fixed in the next release, I think, there has been some work on providing more of the error message text. It is also tracked elsewhere, so I'll close this issue.

**Comment by henriiik** [comment]
Alright, thanks! :)
