### ISSUE TITLE
Cannot find function in module

### ISSUE THREAD

**Issue by LovedByTheLord** [rust-lang-nursery/rls-vscode#262]
Hi,

I'm new to Rust and trying to follow along in the book in chapter 14 where it talkes about [workspaces](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html).  

I'm using Visual Studio Code with the Rust (rls) plug in.  When I get to the step in the book where I call add_one::add_one(num) from main, VS Code has a red squiggly line under add_one and says "cannot find function `add_one` in module `add_one`".  The code compiles just fine so something is going on with the plugin.  

<img width="1792" alt="screen shot 2018-03-01 at 2 38 24 pm" src="https://user-images.githubusercontent.com/17475836/36868603-754d4664-1d5e-11e8-98a2-94d0a7992e32.png">

I'm on version 0.3.2 of the Rust (rls) plugin.
MacBook Pro
OSX 10.13.3

**Comment by nrc** [comment]
With any luck this will be fixed with tomorrow's update of the RLS - I landed a bunch of work improving workspace handling.

**Comment by LovedByTheLord** [comment]
It looks like this is fixed in 0.4.0.  This issue can be closed.

Thanks!

**Comment by inxanedev** [comment]
This is still an issue with the latest Rust plugin.
