### ISSUE TITLE
Status bar message stuck at "RLS: starting up" on newest nightly rls

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rls-vscode#263]
RLS is running and working just fine from what I can tell, but the status bar message says at "starting up". This appears to be new as of `rls-preview 0.126.0-nightly (d4f0b29 2018-02-28)`

**Comment by nrc** [comment]
cc https://github.com/rust-lang-nursery/rls/issues/744

Fixed by #231

**Comment by nrc** [comment]
Yes, this is a purely cosmetic issue, RLS should be working fine behind the scenes

**Comment by nrc** [comment]
This should be fixed by using the new version of the extension (0.4.0)
