### ISSUE TITLE
Use `label` on tasks, rather than `taskName`

### ISSUE THREAD

**Issue by savish** [rust-lang-nursery/rls-vscode#265]
It seems as though the `taskName` property on tasks is being deprecated, so we should probably switch to `label`. However, the tasks themselves still run just fine, so this is likely low-priority for now.

**Comment by duriantang** [comment]
[Migrating to Tasks 2.0.0](https://code.visualstudio.com/docs/editor/tasks#_migrating-to-tasks-200)
according this doc, `tasks.json` upgrade to `2.0.0`, so I created a  #269  fix this.

**Comment by savish** [comment]
Looks like this change is live. Thanks!
