### ISSUE TITLE
No visual indication of activity/progress when updating after a save

### ISSUE THREAD

**Issue by rocallahan** [rust-lang-nursery/rls-vscode#282]
With `"rust.build_on_save": true`, when I make some changes and save, it takes a while for RLS to rerun the build and update the set of errors and warnings. During this time RLS is running at 100% CPU but there is no visual indication in VSCode that anything is happening. The only way I can tell is that RLS-based features like jump-to-definition are blocked.

(With `"rust.build_on_save": false`, I don't know how to trigger a RLS refresh at all...)

**Comment by nrc** [comment]
There should be a spinner and information like which crate is being built in the footer bar. Does that never appear for you?

**Comment by rocallahan** [comment]
There are appear to be two different kinds of updates: one where all my crates are reindexed, and one where only the crate I modified is reindexed. In the latter case I don't get any feedback. In the latter case I sometimes wasn't getting any visual feedback, but I can't reproduce it now. I'll reopen if I can reproduce it.
