### ISSUE TITLE
cfg_test erroneously marking imports as unused

### ISSUE THREAD

**Issue by mooman219** [rust-lang-nursery/rls-vscode#284]
Running: rls-vscode 0.4.0

When running with the flag `rust.cfg_test: true`, rls-vscode will incorrectly mark my use imports as unused, contrary to them actually being used. `cargo check --all` does not produce any warnings when ran on its own.

![image](https://user-images.githubusercontent.com/865769/37888571-2e2501e6-3096-11e8-83cf-eb4e7a5f3a77.png)

Here's a link to the project in the screenshot: [https://github.com/mooman219/storm-engine](https://github.com/mooman219/glplay). Should build just fine on any system.

**Comment by mooman219** [comment]
This problem does not occur when using the `"rust.all_targets": true` configuration value.

**Comment by nrc** [comment]
Tracked in https://github.com/rust-lang-nursery/rls/issues/741
