### ISSUE TITLE
Add the `clippy-preference` option

### ISSUE THREAD

**Issue by danielshaar** [rust-lang-nursery/rls-vscode#298]
This seems to be supported by RLS as of [this commit](https://github.com/rust-lang-nursery/rls/commit/f7031d94562e64135d0dbc90b24004d79145ab9e), but not by the VSC plugin.

**Comment by dlukes** [comment]
I guess with 926b2eb1128f8f2f1e49afec917c68da9f1a2c84, this can now be closed? :)

**Comment by Xanewok** [comment]
@dlukes nice catch, thanks!
