### ISSUE TITLE
Why does it install Nightly?

### ISSUE THREAD

**Issue by mcclure** [rust-lang-nursery/rls-vscode#305]
I installed this vscode extension. It is nice! However, I noticed: When I first installed it, it installed first rust nightly, then it installed RLS. It was as if the vscode setup believed that nightly was necessary in order to boot RLS. However, a Rust user I talked to informed me that RLS has not required nightly since Rust 1.21. The RLS instructions https://github.com/rust-lang-nursery/rls suggest only that you need to install the most current version.

Is the Rust Nightly install actually necessary, or is this just a vestigial quirk of when RLS required nightly?

**Comment by awbacker** [comment]
Just installed `v0.4.2` and got I got two messages from "Rust (rls) (Extension)":

> nightly toolchain not installed.  install?" 

and

> RLS could not set RUST_SRC_PATH for Racer because it could not read the Rust sysroot.

![image](https://user-images.githubusercontent.com/103330/39860648-a4aa7366-5470-11e8-8371-796e564abb2b.png)

**Comment by segevfiner** [comment]
I think the extension parses the output of `rustup show` but it probably changed...

rustup doesn't seem to have stable machine parsable output for this, see https://github.com/rust-lang-nursery/rustup.rs/issues/450.

See: https://github.com/rust-lang-nursery/rls-vscode/blob/3dc3987eb215cb4d72252ea17e853e19023cea48/src/rustup.ts#L193-L212

**Comment by andrekoehler** [comment]
It would be great if `"rust-client.channel": "stable"` was the default setting because rustup installs the stable toolchain by default as well.
