### ISSUE TITLE
Suggestion: Improve syntax highlighting 

### ISSUE THREAD

**Issue by eedahl** [rust-lang-nursery/rls-vscode#317]
Not sure if I'm in the right place, but the syntax highlighting for VS Code seems very limited and unconfigurable. As I've witnessed with others it makes transitioning from Atom rough, and coming from VS Code, it makes transitioning to Atom kind of tempting. Any improvements in this regard would be very nice.

**Comment by jonasbb** [comment]
VS Code uses the syntax highlighting files from Atom.
The syntax highlighting files are shipped with VS Code and not part of the extension, so you might want to file an issue in the vscode repository or directly on the rust atom repository.

**Comment by eedahl** [comment]
Okay, thanks for letting me know! I'll hit up VS Code first and see where it takes me :)
