### ISSUE TITLE
RLS crash with nightly 15/05

### ISSUE THREAD

**Issue by Geobert** [rust-lang-nursery/rls-vscode#319]
Using nightly-x86_64-pc-windows-msvc updated - rustc 1.27.0-nightly (f0fdaba04 2018-05-15)
```
fatal runtime error: memory allocation failed
[Info  - 20:09:33] Connection to server got closed. Server will restart.
fatal runtime error: memory allocation failed
[Info  - 20:09:38] Connection to server got closed. Server will restart.
fatal runtime error: memory allocation failed
[Info  - 20:09:42] Connection to server got closed. Server will restart.
fatal runtime error: memory allocation failed
[Info  - 20:09:45] Connection to server got closed. Server will restart.
fatal runtime error: memory allocation failed
[Error - 20:09:49] Connection to server got closed. Server will not be restarted.
```

**Comment by cynecx** [comment]
I've also gotten this error but it seems fixed with master/upstream. If you need a working rls now, you would have to clone the [rls repository](https://github.com/rust-lang-nursery/rls) and manually build it (Well, it's simply `cargo build --release`). rls-vscode has a setting (`rust-client.rlsPath`) where you can set it to the just-built rls.

**Comment by Geobert** [comment]
I got this with master:
```
[Info  - 20:39:13] Connection to server got closed. Server will restart.
[Info  - 20:39:13] Connection to server got closed. Server will restart.
[Info  - 20:39:13] Connection to server got closed. Server will restart.
[Info  - 20:39:13] Connection to server got closed. Server will restart.
[Error - 20:39:13] Connection to server got closed. Server will not be restarted.
```
No bother, I'll wait :)

**Comment by cynecx** [comment]
Well, that's weird for sure. I suppose this is an issue with rls, so I think it's best if you report this over the rls repo.

**Comment by Geobert** [comment]
It seems it was already done: https://github.com/rust-lang-nursery/rls/issues/871

**Comment by nrc** [comment]
This should be fixed with today's nightly, sorry for the inconvenience.
