### ISSUE TITLE
offer an modern rust-style highligting theme for VSCode?

### ISSUE THREAD

**Issue by NateLing** [rust-lang-nursery/rls-vscode#325]
the vscode  official theme dont support rust code highligting  well,any plan to offer an modern rust-style highligting theme? 

1. the generic、struct and enum variable should be highligting in any where
2. reference and pointer should be more striking

any more?

**Comment by nrc** [comment]
Syntax highlighting for Rust is built-in to VSCode, so this would have to be a change to VSCode, not our extension. It is (I think) a good idea to update that syntax highlighting.
