### ISSUE TITLE
Getting: Activating extension `JanathanTurner.rls_vscode` failed: undefined

### ISSUE THREAD

**Issue by jannickj** [rust-lang-nursery/rls-vscode#33]
On ubunt 16.04
VSCode: 1.8.1
npm: 3.10.10
node: 6.9.4
Commit: e7f8a8b159265e76d20ba48945f851d3c90095ef(master)

Developer console: Activating extension `JanathanTurner.rls_vscode` failed: undefined

I have RLS_ROOT pointing at a built rls.

**Comment by Nimamoh** [comment]
I have this issue too.
archlinux 64 bits
VSCode: 1.8.1
npm --version : 4.0.5
node --version : v7.4.0
commit: e7f8a8b159265e76d20ba48945f851d3c90095ef
env | grep RLS: RLS_ROOT=/opt/rls
exported rust dynamic libraries. rls is running fine on the shell.

When I launch the extension:

> /opt/visual-studio-code/code --debugBrkPluginHost=8729 --extensionDevelopmentPath=/opt/rls_vscode 
> Échec de l'activation de l'extension 'JonathanTurner.rls_vscode' : {1}.
> Activating extension `JonathanTurner.rls_vscode` failed:  undefined
> Here is the error stack:  undefined

**Comment by jonasbb** [comment]
@Nimamoh The `{1}` looks strange. Wild guess here, but I think I got a similar error before I installed the typescript compiler.

**Comment by Nimamoh** [comment]
Ok, I juste installed typescript compiler with this command:

> npm install -g typescript

However, I still have the same error :s

**Comment by jannickj** [comment]
@Nimamoh @jonasbb  It is the same for me installing tsc didn't change anything.

**Comment by Xanewok** [comment]
@jannickj I had the same problem just now.  
Try running `npm install` again in `rls_vscode` directory and try running editor again with `code .`.
Hope this helps.
