### ISSUE TITLE
Incorrect matching angle bracket with Fn traits in generics

### ISSUE THREAD

**Issue by Ristarg** [rust-lang-nursery/rls-vscode#332]
![image](https://user-images.githubusercontent.com/18281341/40923860-18bf4550-6840-11e8-9fc9-35ec0290ce9d.png)

The return type arrow `->` is being incorrectly parsed as a closing angle bracket. This probably doesn't come up often, but would be nice if this was accounted for.

Extension version 0.4.5, VS Code version 1.23.1

**Comment by jonasbb** [comment]
Syntax highlighting is built into VS Code and is not part of this extension. As such it is better to directly open a bug report on the VS Code repository or directly in the [third-party repository](https://github.com/zargony/atom-language-rust/issues) which they are using.

**Comment by Ristarg** [comment]
I see, thank you.
