### ISSUE TITLE
No auto-completion for macro results

### ISSUE THREAD

**Issue by Noah11012** [rust-lang-nursery/rls-vscode#338]
When using a macro such as `vec!` and then trying to call a method on the vector, no auto-completion comes up.

Code:

```
fn main() {
    let v = vec![1, 2, 3];
    v. // No auto-completion appears
}
```

**Comment by nrc** [comment]
This is a problem with Racer, which is embedded in the RLS. I don't think there is anything actionable here - Racer can't be made to understand macros, but eventually we will use the compiler instead.

**Comment by lnicola** [comment]
@JeanMertz your latter sample isn't a macro, so you should probably file an issue.
