### ISSUE TITLE
RLS plugin stops suggesting autocomplete after error

### ISSUE THREAD

**Issue by drorlevywork** [rust-lang-nursery/rls-vscode#341]
this happens quite frequently at the moment, having some code in the editor\saved to disk which fails compilation seems to be the main cause of the issue.
once it happens the rls cannot recover and the only way to retry is to restart vscode entirely (ctrl+p and  "restart rls", "update rls" and "reload window" seem ineffective).

attached is the log from the entire session, though i suspect the end is the main relevant part
[vscode-rls-crash.txt](https://github.com/rust-lang-nursery/rls-vscode/files/2111025/vscode-rls-crash.txt)

**Comment by nrc** [comment]
Do you have a link to the code which is causing this situation? Ideally with instructions for how to get it into the error state? Which channel (nightly/stable) are you using?

**Comment by drorlevywork** [comment]
unfortunately it is proprietary, so i cannot easily share it.
i could try to replicate as this seems to happen all the time actually.
seems to simply require code which fails compilation for too long(i.e. multiple edits).

**Comment by jhgg** [comment]
I've had this happen too  (pretty consistently), but it seems to be solved when using nightly for `rust-client.channel`

**Comment by nrc** [comment]
@drorlevywork could you check with nightly RLS if you're not using it please? If it is still broken, then a minimal test case I could work with would be really useful, thanks!

**Comment by drorlevywork** [comment]
one day later it seems that nightly indeed improved the stability greatly, i still see some errors in the output window of rls occasionally, but it seems to work ok most of the time.
i suppose this issue could be closed in the meanwhile then?
