### ISSUE TITLE
Not able to download toolchain

### ISSUE THREAD

**Issue by Raj2032** [rust-lang-nursery/rls-vscode#345]
When I installed this addon I was prompted to install Toolchain so when I clicked on it I got this error
https://discourse-cdn-sjc1.com/business5/uploads/rust_lang/original/2X/d/d1d55e667511d5538b141de83b203327d8178c3c.png

I have no idea what is going on. Could somebody please help me?

**Comment by jonasbb** [comment]
This is probably the rustup installation issue: https://github.com/rust-lang/rust/issues/51699

**Comment by mati865** [comment]
Yeah, should be fixed by tomorrow.
