### ISSUE TITLE
dyn is not highlighted as a keyword

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rls-vscode#349]
Using Rust 2018 edition, `dyn` is not highlighted as a keyword.

VSCode extension v0.4.5

**Comment by nrc** [comment]
The syntax highlighter comes with VSCode, not the extension so this will need fixing there.

**Comment by doxxx** [comment]
I'm confused. I click the Repository link in the extension info page in VS Code and it brought me here. Is this not the correct repo?

**Comment by nrc** [comment]
For syntax highlighting you need the main VSCode repo, not the extension one: https://github.com/Microsoft/vscode/tree/master/extensions/rust/syntaxes

**Comment by doxxx** [comment]
Any particular reason why the syntax highlighting is not part of the extension? According to the docs, it looks like it's possible... That would allow the extension to rev independently of VSCode itself.

**Comment by nrc** [comment]
Not really, other than there didn't seem any point duplicating what VSCode already has built-in. If you wanted to try using our own highlighter, then feel free to have a go, but I don't know if/how it will work.
