### ISSUE TITLE
Are vscode workspaces supported?

### ISSUE THREAD

**Issue by aloucks** [rust-lang-nursery/rls-vscode#354]
I'm frequently seeing hover-over docs failing to load when using multiple projects in vscode workspaces. With TRACE logging enabled I can confirm that `"contents": []` on the jsonrpc response. When the projects are loaded separately (`Open Folder` vs `Open Workspace`) things mostly work normally. It looks like RLS might only be compiling one of the projects in workspace mode. 

Note that this are distinct projects that are not part of a cargo workspace.

**Comment by nrc** [comment]
They are on master, but it's a bit buggy so it's not in a release yet. Coming soon!
