### ISSUE TITLE
Ctrl-click navigation is not possible for enum type but possible for enum members

### ISSUE THREAD

**Issue by dremon** [rust-lang-nursery/rls-vscode#383]
Consider the following example:

```rust
enum MyEnum { Foo }

fn main() {
    let v = MyEnum::Foo;
}
```

When pressing Ctrl and hovering mouse over MyEnum::Foo it is possible to go to Foo definition but not MyEnum definition.

**Comment by nrc** [comment]
In general, for paths like `foo::bar::baz` we only have information for `baz`, not for `foo` and `bar`. This is a limitation in the compiler, but I hope to fix it at some point.

Tracked in nrc/rls-analysis#109
