### ISSUE TITLE
No error squiggles

### ISSUE THREAD

**Issue by roddyaj** [rust-lang-nursery/rls-vscode#401]
I've been writing rust code using Eclipse, but thought I'd give VSCode a try.  I have the RLS plugin installed and my project imported.  However, I never see any error squiggles, even when my code is blatantly wrong, and this unfortunately is a dealbreaker for me.  Please let me know what additional information I can provide and how to get it.  The only error I see (at startup) is: "Cargo failed: Error compiling dependent crate"

**Comment by jens1o** [comment]
What is the crate you are working with?

**Comment by roddyaj** [comment]
It's my own crate.  Unfortunately for debug purposes, it's a private repo.

**Comment by roddyaj** [comment]
Any ideas on this one?  Can I provide logs or any other info to help debug?

**Comment by roddyaj** [comment]
Before I saw your comment, I re-installed rust and cargo, reinstalled VS Code, set VS Code to use rust nightly, re-installed the Rust/RLS stuff into VS Code, restarted, and now it's working.  I wish I could say which of those things fixed it!
