### ISSUE TITLE
Can't switch to nightly channel

### ISSUE THREAD

**Issue by Kane-Sendgrid** [rust-lang-nursery/rls-vscode#409]
When switching to `"rust-client.channel": "nightly",` rls doesn't start. Trying to restart RLS from command palette results in: `command rls.restart not found`.

Stable channel works fine.

**Comment by Systemcluster** [comment]
See https://github.com/rust-lang-nursery/rls/issues/1011

**Comment by Kane-Sendgrid** [comment]
@Systemcluster I've tried to downgrade nightly and manually install RLS - install worked, but vs code still doesn't recognize it - in nightly channel it still doesn't start rls server, when trying manually reinstall it - again `command rls.restart not found`

**Comment by Kane-Sendgrid** [comment]
trace reports: 
`[2919:0825/093823.030074:INFO:CONSOLE(2386)] "Error: command 'rls.restart' not found", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js (2386)`

**Comment by Kane-Sendgrid** [comment]
Thanks! I think this fixed it. I had to completely remove vscode though, otherwise it kept telling that rls.restart wasn't found
