### ISSUE TITLE
Auto add use/import does not work

### ISSUE THREAD

**Issue by autoferrit** [rust-lang-nursery/rls-vscode#415]
Code example, i simply started with this file from the rust book

```rust
fn main() {
    println!("Guess the number");
    println!("Please input your guess");

    let mut guess = String::new();

    io::stdin()
        .read_line(&mut guess)
        .expect("Failed to read line");

    println!("You guessed: {}", guess);
}
```
the line `io::stdin()` has a line under the `io` specifying it cannot be found. because it needs to be imported. Per another issue on here https://github.com/rust-lang-nursery/rls-vscode/issues/221 this should work by showing a small lightbulb in the ui near the used `io` code. But nothing shows.
![image](https://user-images.githubusercontent.com/89895/44703443-81664600-aa4c-11e8-818d-f150a6ef91e1.png)

Running `fix` via the command palette also doesn't have any available fixes.

vscode on linux (arch)
```bash
$ code --version
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64
```

**Comment by nrc** [comment]
This is a bug in rustc. Tracked at https://github.com/rust-lang/rust/issues/55338
