### ISSUE TITLE
How to disable automatic line breaks in formatter?

### ISSUE THREAD

**Issue by ivxvm** [rust-lang-nursery/rls-vscode#416]
When I write this and save:
```
    let board = stdin.lock().lines().map(|r| r.unwrap()).take(3).collect::<String>();
```
It is automatically formatted like this:
```
    let board = stdin
        .lock()
        .lines()
        .map(|r| r.unwrap())
        .take(3)
        .collect::<String>();
```
Is there a way to prevent this or at least increase the line length where it begins (75) without disabling autoformatting completely? I've tried changing standard vs code settings for wrapping and rulers but it doesn't affect rls.

**Comment by jonasbb** [comment]
Formatting is done by [rustfmt](https://github.com/rust-lang-nursery/rustfmt). The link also explains how to setup a configuration file.

**Comment by ivxvm** [comment]
Thanks, I got the desired behavior by creating `rustfmt.toml` with just a single line:

```
max_width = 120
```
