### ISSUE TITLE
Expand 'goto definition' to all `use` components

### ISSUE THREAD

**Issue by kellytk** [rust-lang-nursery/rls-vscode#418]
It would be helpful for learning and code exploration if 'goto definition' support was added to all `use` components.  It appears that only the last component, when not `*`, supports 'goto definition.'

For example, with `use actix::prelude::*;` 'goto definition' is not supported at all.  With `use std::fs`, 'goto definition' is supported only for `fs`.

**Comment by nrc** [comment]
This is a duplicate, but in any case there is a PR in Rust which addresses it: https://github.com/rust-lang/rust/pull/54145
