### ISSUE TITLE
RLS could not be started

### ISSUE THREAD

**Issue by nabeelomer** [rust-lang-nursery/rls-vscode#426]
I have the rls-vscode extension installed and it used to work, but now when I open vscode and open a rust file a prompt shows up saying "RLS not installed. Install?" I clicked yes and then I get 2 prompts, "Couldn't start client Rust Language Server" and "Could not install RLS component (rls-preview)".

VSCode v1.28.0-insider
rls-vscode v0.4.10 preview

**Comment by nabeelomer** [comment]
Turns out I just needed to update Rust.

**Comment by shehzadaliqadri** [comment]
Had you found solution for your problem? i also face same problem.
