### ISSUE TITLE
goto definition only work "once"?

### ISSUE THREAD

**Issue by huangjj27** [rust-lang-nursery/rls-vscode#434]
I'm using vim-mode and use the key `Ctrl + ]` to go to definitions of other functions, then after jumping I can't use the `Ctrl + ]` key to jump to another function's definition. I could only use the function of goto definition only after I return to the source with `Ctrl + T`. Having searched the GitHub issues but see no similar issue.

## Environment
rust:
rustc 1.30.0-nightly (bb0896af1 2018-09-29), with `rls-preview`, `rust-src`, `rust-analysis` installed and updated,
no stand alone racer installed

**Comment by jonasbb** [comment]
Are you using the goto definition function in your current crate/code or in a separate crate/stdlib? The goto definition feature only works in your code. It is possible to use it on a library type, say `Vec`, and it will take you to the stdlib source code, but then it won't work anymore. If you use it on a type defined in your own code it should continue working.

**Comment by huangjj27** [comment]
@jonasbb Yes, I used this feature for extern crates and haven't known about that the feature is only for my code. Tested it, thanks!
