### ISSUE TITLE
Find all references gives false results

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang-nursery/rls-vscode#44]
e.g. searching for references of  overscroll_amount() in clip_scroll_node.rs of webrender/webrender gives results that include "if overscrolling {" and "else if overscrolling &&"

**Comment by jonathandturner** [comment]
I wonder if this is related to https://github.com/rust-lang-nursery/rls/issues/239

**Comment by nrc** [comment]
Is this still a problem? I hope it is fixed.
