### ISSUE TITLE
"File not found" when stepping into source code

### ISSUE THREAD

**Issue by c7hm4r** [rust-lang-nursery/rls-vscode#47]
When debugging and you try to step into std library code (for example `HashMap::new()`) in VS Code the following error message is displayed:

> Unable to open 'map.rs': File not found (/buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/collections/hash/map.rs).

`RUST_SRC_PATH` environment variable for Racer is [set up](https://github.com/phildawes/racer/blob/master/README.md#configuration)

OS: Ubuntu 16.04
VSCode: 1.11.1
rust-toolchain: nightly-2017-04-11
rls: d385f447a55e974d0ebdc40948f40c18b96e634e
rls_vscode: 40044e967916cbcfc73add60bfa672713470f27d

**Comment by jonathandturner** [comment]
Debugging doesn't use the same environment variables as Racer does.  In VS, when you're debugging, you have to take the step to point VS at the source code yourself.

What plugins are you using to enable debugging of Rust in VSCode?

**Comment by c7hm4r** [comment]
I use [Native Debug](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) version 0.18.0. My launch.json looks like this:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "LLDB",
      "type": "lldb-mi",
      "request": "launch",
      "target": "./target/debug/my-project",
      "cwd": "${workspaceRoot}",
      "preLaunchTask": "build"
    },
    {
      "name": "LLDB Test",
      "type": "lldb-mi",
      "request": "launch",
      "target": "./target/debug/my-project-0123456789abcdef",
      "cwd": "${workspaceRoot}",
      "preLaunchTask": "build-test",
      "env": {
        "RUST_BACKTRACE": "1"
      }
    }
  ]
}
```

`preLaunchTask`s are configured in settings.json:
```
{
  "version": "0.1.0",
  "command": "yarn",
  "isShellCommand": true,
  "args": [],
  "showOutput": "always",
  "suppressTaskName": false,
  "tasks": [
    {
      "taskName": "build"
    },
    {
      "taskName": "build-test"
    }
  ]
}
```

package.json:
```
{
  // …
  "scripts": {
    "build": "rustup run stable cargo build",
    "build-test": "bash -c 'rustup run stable cargo test || true'",
  }
}
```

And the missing versions:
```
$ rustup run stable rustc --version
rustc 1.16.0 (30cf806ef 2017-03-10)
$ rustup run stable cargo --version
cargo-0.17.0-nightly (f9e5481 2017-03-03)
```

**Comment by c7hm4r** [comment]
What do you mean by "you have to take the step to point VS at the source code yourself"? How to accomplish that?

**Comment by jonathandturner** [comment]
This assumes you're using VS instead of VS Code.  If you're using VS, VS will pop up a dialog that asks you to locate the file it's looking for so the debugger can show it.

**Comment by nrc** [comment]
We now set `RUST_SRC_PATH` automatically, so this should be fixed.
