### ISSUE TITLE
stderr not being written to console

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#66]
Even with `HIDE_WINDOW_OUTPUT = false`

**Comment by Xanewok** [comment]
Asked also over at https://github.com/Microsoft/vscode-languageserver-node/issues/223

**Comment by nrc** [comment]
Even after #68, this is not working for me.

**Comment by nrc** [comment]
Fixed now

**Comment by Xanewok** [comment]
Workaround is not needed as of https://github.com/Microsoft/vscode-languageserver-node/commit/8ed63637d95e1dbd7ad0b6e5d71195a7a88943b2 !
