### ISSUE TITLE
Update RLS

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#70]
When necessary. I guess we'd have to restart the RLS afterwards?

**Comment by mominul** [comment]
Hmm, there should be a button for restarting rls. When I edit source, like adding a new function on top of another function rls shows hint for the previous function. So there should be a button that will restart the analysis.

**Comment by nrc** [comment]
Analysis restarts automatically after every change, you should see the effects fairly soon unless you have a large crate or the RLS has crashed (you should see some message in the latter case). What project are you working with?

**Comment by mominul** [comment]
My project is very little https://github.com/OpenBangla/bengali-phonetic-parser-rs . It is also my first crate :smile: Here you can see, the hint is showing function signature `fn (rule: &json::JsonValue) -> PhoneticParser` but the signature should be `fn () -> bool`

![screenshot from 2017-07-25 11-38-47](https://user-images.githubusercontent.com/9459891/28557434-360a55f0-712e-11e7-9dbb-39c8e0fc944a.png)

**Comment by nrc** [comment]
There is a command for updating the RLS and an option to do it automatically.
