### ISSUE TITLE
Goto-def hover gives errors

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang-nursery/rls-vscode#74]
If I hold `command` on macOS, and hover over a symbol that I can't goto def, I see this error in the output:

```
[Error - 1:47:26 PM] Request textDocument/definition failed.
  Message: GotoDef failed to complete successfully
  Code: -32601 
```

**Comment by jtremback** [comment]
Pretty annoying

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang-nursery/rls/commit/220116ce0792fd93a970974c63dc62c34a12c9d7
