### ISSUE TITLE
RLS crashes.  No obvious way to view logs or get any other information.

### ISSUE THREAD

**Issue by TyOverby** [rust-lang-nursery/rls-vscode#76]
Wish My bug report could have more details than this :(

```
[Info  - 10:40:22 PM] Connection to server got closed. Server will restart.
[Info  - 10:40:24 PM] Connection to server got closed. Server will restart.
[Info  - 10:40:27 PM] Connection to server got closed. Server will restart.
[Info  - 10:40:29 PM] Connection to server got closed. Server will restart.
[Error - 10:40:31 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by nrc** [comment]
Thanks for the bug report. What project did you open?

(There's a PR to reveal more debug logs, so that should be in the next version released later this week).

**Comment by TyOverby** [comment]
https://github.com/TyOverby/implicit-gpu.  I opened the testsuite folder

**Comment by nrc** [comment]
I tried to reproduce this but could not. It did take rather a long time to build, but building completed and I could use IDE functions. You could try running `rustup update` to get the latest Rust compiler and RLS (there are some fixes in there since yesterday). It's also possibly fixed on master, but not nightly.

**Comment by TyOverby** [comment]
I ran `rustup update` and it still crashes.

**Comment by nrc** [comment]
I'll release new versions of the RLS and vscode plugin early next week. Hopefully that will fix it, otherwise I'll try harder to reproduce locally.

**Comment by TyOverby** [comment]
If you could also enable more verbose logging  or stack traces, I wouldn't mind looking into this myself.

**Comment by nrc** [comment]
Yep! That's in the next release of the extension

**Comment by TyOverby** [comment]
perfect!  Thanks!

**Comment by TyOverby** [comment]
I just updated my RLS.  Still crashes without any logs or error messages.

**Comment by nrc** [comment]
You can now get logging by setting the `rust-client.showStdErr` setting to true in your VSCode configuration. To get more logging, you can relauch VSCode with `RUST_LOG=rls=debug`.

**Comment by TyOverby** [comment]
Perfect.  I had `RLS_ROOT` set from months ago, and so it was building a very old version of RLS.  Now that I fixed that, it appears to be working!

Thanks!
