### ISSUE TITLE
RLS crashed in RLS-Vscode but not in Vscode-rust or Commandline

### ISSUE THREAD

**Issue by zmanian** [rust-lang-nursery/rls-vscode#82]
When I open https://github.com/isislovecruft/ed25519-dalek in vscode-rust or on the commandline, RLS starts up without a problem.

I'm trying the RLS-vscode from the market place and it crashes.

Will update with more debug info from the next release.

**Comment by nrc** [comment]
This is https://github.com/rust-lang-nursery/rls/issues/169

You can work around this by setting `rust.cfg_test` to false in your settings. (You might also need to `rustup update` for that to work).

We should be able to report an error to the user here, at least. I'm not sure why we're not.

**Comment by nrc** [comment]
Should be fixed
