### ISSUE TITLE
should we/can we install Rustup?

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#88]
If the user has Rustup we'll do the rest, but we won't install Rustup. I assume we can (but I'm not sure). Should we do this? (We would ask permission of course). Would we need to do different things on different platforms?

**Comment by Nashenas88** [comment]
The installer for `rustup` on Windows is not the same as in Mac or Linux. You'd have to know to install something else. Are there existing patterns of extensions that install something onto your system (after requesting of course)?

**Comment by nrc** [comment]
We do
