### ISSUE TITLE
GotoDef failed to complete successfully

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rls-vscode#94]
When I use Go to Definition (`f12`) few times, rls fails with the following error message:
```
[Error - 23:53:49] Request textDocument/definition failed.
  Message: GotoDef failed to complete successfully
  Code: -32601 
```
### Environment
* Visual Studio Code: `1.14.2`
* rls: `0.1.0-nightly (ee92edb 2017-07-22)`
* rls-vscode: `0.1.0`
* OS: Arch Linux (`4.11.9-1`)

**Comment by topecongiro** [comment]
After creating this issue I found a very similar one in #74.
However, I am using the latest rls which should include the fix (https://github.com/rust-lang-nursery/rls/commit/220116ce0792fd93a970974c63dc62c34a12c9d7), but it is still giving the same error messages.

**Comment by nrc** [comment]
What project were you looking at? When you tried to goto def, which symbol were you on?

**Comment by mominul** [comment]
I always see this kind of error to occur when I ctrl+click on any std functions.

**Comment by doxxx** [comment]
I get this error when I hold down Control and mouse over comments.

**Comment by doxxx** [comment]
Also when hovering over the `derive` or `...` in `#[derive(...)]` lines.

**Comment by doxxx** [comment]
Updating to the latest rust nightly toolchain (rustc 1.20.0-nightly (598eddf4f 2017-07-24)) resolved these errors for me.

**Comment by doxxx** [comment]
Although I still get a slightly different error when hovering of `std` types like std::fs::File at actual usage sites:

```
[Error - 6:13:27 PM] Request textDocument/definition failed.
  Message: GotoDef failed to complete successfully
  Code: -32603 
```

**Comment by topecongiro** [comment]
@nrc I was looking at rustfmt, rust, and my personal project. Symbols were local variables, macros, functions and structs, both internal and external.

However, when I start vscode from the shell, the issue seems disappear.

**Comment by nrc** [comment]
This should be fixed with latest RLS

**Comment by doxxx** [comment]
Verified using rustc/rls nightly ba1d065ff 2017-08-06.
