### ISSUE TITLE
TypeError: Cannot read property 'writer' of undefined

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rls-vscode#95]
When I open a `.rs` file in VSCode with this extension enabled, I get the following error in the Rust Language Server output window:

> [Error - 4:47:17 PM] Starting client failed
> TypeError: Cannot read property 'writer' of undefined
>     at server.then (C:\Users\Gordon\.vscode\extensions\rust-lang.rust-0.1.0\node_modules\vscode-languageclient\lib\main.js:111:25)

I have rust stable and nightly installed using rustup prior to installing this extension:

> stable-x86_64-pc-windows-msvc unchanged - rustc 1.19.0 (0ade33941 2017-07-17)
> nightly-x86_64-pc-windows-msvc updated - rustc 1.20.0-nightly (15aa15b03 2017-07-21)

I had previously been using the `kalitaalexey.vscode-rust` extension but disabled it before trying this one. I have no rust related settings in my VSCode user/workspace settings.

**Comment by nrc** [comment]
Are you opening a single file, or a Rust project? There is a known bug with the former. By the latter, I mean open a folder in VSCode which contains a Cargo.toml and src directory. (Not the src directory itself).

**Comment by doxxx** [comment]
I'm opening a project rooted at the directory containing the Cargo.toml and the src directory.

**Comment by nrc** [comment]
Could you try running code with `--verbose` please?

**Comment by doxxx** [comment]
I'm assuming you mean `code --verbose .` in my project dir?

Of course, now it's working. :)

The only thing I can think of that might have changed is that I had an old version of rustfmt installed (0.7.1) which I upgraded to resolve a formatting bug.

It is taking it's sweet time to run the analysis though -- 10min so far and it's a small project.

**Comment by nrc** [comment]
We have a couple of patches in the work to speed up that initial analysis. There was another report on Twitter about vscode being a bit finicky about starting up the extension. We haven't yet been able to reproduce.
